<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1c5eb1a8-781a-44ed-883b-df5fc37e816b</testSuiteGuid>
   <testCaseLink>
      <guid>813b55b4-f0b6-4459-8795-6a77fcceec91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8d72ceab-98c8-47c6-98e1-a5b225c6b3cd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8d72ceab-98c8-47c6-98e1-a5b225c6b3cd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>5a41fc58-6096-43a1-a6f4-a96da75fd5d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8d72ceab-98c8-47c6-98e1-a5b225c6b3cd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>35c7fdc8-0097-4b31-b3a5-46bc5c07eadf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
